-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\my_hdlcoder_sqrt_bitset_control\Sqrt_pkg.vhd
-- Created: 2024-12-22 16:30:51
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Sqrt_pkg IS
  TYPE vector_of_unsigned18 IS ARRAY (NATURAL RANGE <>) OF unsigned(17 DOWNTO 0);
END Sqrt_pkg;

