-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\hdlcoder_simple_up_counter\HDL_DUT_tb.vhd
-- Created: 2024-12-21 22:20:45
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
USE work.HDL_DUT_tb_pkg.ALL;

ENTITY HDL_DUT_tb IS
END HDL_DUT_tb;


ARCHITECTURE rtl OF HDL_DUT_tb IS

  -- Component Declarations
  COMPONENT HDL_DUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          count_threshold                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          alphaEnable                     :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          out_rsvd                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_DUT
    USE ENTITY work.HDL_DUT(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL rawData_count_threshold          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL rawData_alphaEnable              : std_logic;
  SIGNAL out_rsvd_done                    : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL out_rsvd_done_enb                : std_logic;  -- ufix1
  SIGNAL out_rsvd_addr                    : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL out_rsvd_active                  : std_logic;  -- ufix1
  SIGNAL holdData_alphaEnable             : std_logic;
  SIGNAL alphaEnable_offset               : std_logic;
  SIGNAL alphaEnable_1                    : std_logic;
  SIGNAL holdData_count_threshold         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_threshold_offset           : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_threshold_1                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL count_threshold_2                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL out_rsvd                         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL out_rsvd_enb                     : std_logic;  -- ufix1
  SIGNAL out_rsvd_lastAddr                : std_logic;  -- ufix1
  SIGNAL out_rsvd_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL out_rsvd_addr_delay_1            : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL out_rsvd_expected                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL out_rsvd_ref                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL out_rsvd_testFailure             : std_logic;  -- ufix1

BEGIN
  u_HDL_DUT : HDL_DUT
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              count_threshold => count_threshold_2,  -- uint8
              alphaEnable => alphaEnable_1,
              ce_out => ce_out,
              out_rsvd => out_rsvd  -- uint8
              );

  -- Data source for count_threshold
  rawData_count_threshold <= to_unsigned(16#0F#, 8);

  -- Data source for alphaEnable
  rawData_alphaEnable <= '1';

  out_rsvd_done_enb <= out_rsvd_done AND rdEnb;

  
  out_rsvd_active <= '1' WHEN out_rsvd_addr /= to_unsigned(16#32#, 6) ELSE
      '0';

  -- holdData reg for Constant1_out1
  stimuli_Constant1_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_alphaEnable <= 'X';
    ELSIF clk'event AND clk = '1' THEN
      holdData_alphaEnable <= rawData_alphaEnable;
    END IF;
  END PROCESS stimuli_Constant1_out1_process;

  stimuli_Constant1_out1_1: PROCESS (rawData_alphaEnable, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      alphaEnable_offset <= holdData_alphaEnable;
    ELSE
      alphaEnable_offset <= rawData_alphaEnable;
    END IF;
  END PROCESS stimuli_Constant1_out1_1;

  alphaEnable_1 <= alphaEnable_offset AFTER 2 ns;

  -- holdData reg for Constant_out1
  stimuli_Constant_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_count_threshold <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_count_threshold <= rawData_count_threshold;
    END IF;
  END PROCESS stimuli_Constant_out1_process;

  stimuli_Constant_out1_1: PROCESS (rawData_count_threshold, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      count_threshold_offset <= holdData_count_threshold;
    ELSE
      count_threshold_offset <= rawData_count_threshold;
    END IF;
  END PROCESS stimuli_Constant_out1_1;

  count_threshold_1 <= count_threshold_offset AFTER 2 ns;

  count_threshold_2 <= std_logic_vector(count_threshold_1);

  snkDonen <=  NOT check1_done;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  
  rdEnb <= tb_enb_delay WHEN check1_done = '0' ELSE
      '0';

  clk_enable <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF check1_done = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  out_rsvd_enb <= ce_out AND out_rsvd_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 50
  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out_rsvd_addr <= to_unsigned(16#00#, 6);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF out_rsvd_enb = '1' THEN
        IF out_rsvd_addr >= to_unsigned(16#32#, 6) THEN 
          out_rsvd_addr <= to_unsigned(16#00#, 6);
        ELSE 
          out_rsvd_addr <= out_rsvd_addr + to_unsigned(16#01#, 6);
        END IF;
      END IF;
    END IF;
  END PROCESS c_3_process;


  
  out_rsvd_lastAddr <= '1' WHEN out_rsvd_addr >= to_unsigned(16#32#, 6) ELSE
      '0';

  out_rsvd_done <= out_rsvd_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      check1_done <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF out_rsvd_done_enb = '1' THEN
        check1_done <= out_rsvd_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  out_rsvd_unsigned <= unsigned(out_rsvd);

  out_rsvd_addr_delay_1 <= out_rsvd_addr AFTER 1 ns;

  -- Data source for out_rsvd_expected
  out_rsvd_expected_fileread: PROCESS (out_rsvd_addr_delay_1, tb_enb_delay, ce_out)
    FILE fp: TEXT open READ_MODE is "out_rsvd_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(7 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    out_rsvd_expected <= unsigned(read_data(7 DOWNTO 0));
  END PROCESS out_rsvd_expected_fileread;

  out_rsvd_ref <= out_rsvd_expected;

  out_rsvd_unsigned_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      out_rsvd_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND out_rsvd_unsigned /= out_rsvd_ref THEN
        out_rsvd_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in out_rsvd_unsigned: Expected " & to_hex(out_rsvd_ref) & (" Actual " & to_hex(out_rsvd_unsigned))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS out_rsvd_unsigned_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF check1_done = '1' THEN
        IF out_rsvd_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

