%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [coeff_Q1,x_min_Q2,Q0,Q1,Q2] = GoertzelCalc_wrapper_fixpt(x,coeff)
    fm = get_fimath();
    x_in = fi( x, 1, 16, 14, fm );
    coeff_in = fi( coeff, 0, 16, 15, fm );
    [coeff_Q1_out,x_min_Q2_out,Q0_out,Q1_out,Q2_out] = GoertzelCalc_fixpt( x_in, coeff_in );
    coeff_Q1 = double( coeff_Q1_out );
    x_min_Q2 = double( x_min_Q2_out );
    Q0 = double( Q0_out );
    Q1 = double( Q1_out );
    Q2 = double( Q2_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Round',...
	     'OverflowAction', 'Saturate',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
